services:
  frontend:
    container_name: frontend

    image: recipe_helper_frontend

    build:
      context: ./frontend
      dockerfile: Dockerfile

    ports:
      - '3000:3000'

    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules

    command: pnpm run dev

  backend:
    container_name: backend

    image: recipe_helper_backend

    build:
      context: ./backend
      dockerfile: Dockerfile

    environment:
      - OLLAMA_HOST=http://ollama:11434

    ports:
      - '8080:8080'

    volumes:
      - ./backend:/backend

    command: sh -c "go install github.com/air-verse/air@latest &&
      air -c .air.toml"

  database:
    container_name: database

    image: recipe_helper_database

    build:
      context: ./database
      dockerfile: Dockerfile

    ports:
      - '5432:5432'

    volumes:
      - ./database:/database

  ollama:
    container_name: ollama

    image: recipe_helper_ollama

    build:
      context: ./ollama
      dockerfile: Dockerfile

    ports:
      - '11434:11434'

    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

    command: ollama serve && ollama run mistral
