name: Database Docker Build

on:
  push:
    branches: [ "main" ]

env:
  DOCKER_REPOSITORY: nave321/recipe_helper

jobs:
  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./database/Dockerfile
        push: true
        tags: ${{ env.DOCKER_REPOSITORY }}/recipe_helper_database:latest,${{ env.DOCKER_REPOSITORY }}/recipe_helper_database:${{ github.sha }}